"""Print the schema as PostgreSQL DDL, without connecting to a database.

Useful as a review artifact and as a fast check that every mapper, foreign key, and
relationship actually compiles.

    .venv/Scripts/python -m scripts.schema_sql
"""

from sqlalchemy.dialects import postgresql
from sqlalchemy.orm import configure_mappers
from sqlalchemy.schema import CreateIndex, CreateTable

import app.models  # noqa: F401  (registers every mapper)
from app.db.base import Base


def main() -> None:
    configure_mappers()
    dialect = postgresql.dialect()

    print("-- Path Pilot schema — generated by scripts/schema_sql.py")
    print("CREATE EXTENSION IF NOT EXISTS vector;\n")

    for table in Base.metadata.sorted_tables:
        print(str(CreateTable(table).compile(dialect=dialect)).strip() + ";\n")
        for index in table.indexes:
            print(str(CreateIndex(index).compile(dialect=dialect)).strip() + ";")
        if table.indexes:
            print()

    print(f"-- {len(Base.metadata.tables)} tables")


if __name__ == "__main__":
    main()
